language: generic

branches:
  # whitelist
  only:
    - pipe-fibonacci/master
  # blacklist
  except:
    - master

services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t fibonacci-client-test ./client

script:
  - docker run -e CI=true fibonacci-client-test npm test -- --coverage

after_success:
  - docker build -t sougotsu/fibonacci-client ./client
  - docker build -t sougotsu/fibonacci-nginx ./nginx
  - docker build -t sougotsu/fibonacci-server ./server
  - docker build -t sougotsu/fibonacci-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD_PIPE" | docker login -u "$DOCKER_ID_PIPE" --password-stdin

  # Take those images and push them to docker hub
  - docker push sougotsu/fibonacci-client
  - docker push sougotsu/fibonacci-nginx
  - docker push sougotsu/fibonacci-server
  - docker push sougotsu/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "pipe-fibonacci"
  env: "PipeFibonacci-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-774154012305"
  bucket_path: "pipe-fibonacci"
  on:
    branch: pipe-fibonacci/master
  access_key_id: $AWS_ACCESS_KEY_PIPE
  secret_access_key: $AWS_SECRET_KEY_PIPE