# Use an existing docker image as a base
FROM node:alpine

# Setting working directory
WORKDIR /app

# Copy package json to image/container before rest of files
# to avoid unnecesary rebuilds
COPY ./package.json ./

# Download an install a dependency
RUN npm install

# Copy files to image /container
COPY ./ ./

# Tell the image what to do when it starts as a container
CMD ["npm", "run", "dev"]